### ISSUE TITLE
Not compilable on CUDA 7.5

### ISSUE THREAD

**Issue by ET-Chan** [tkocisky/oxnn#8]
While building on CUDA 7.5, following error messages were printed

```
/tmp/luarocks_oxnn-scm-1-943/oxnn/src/LSTM12Part2.cu(102): error: this declaration has no storage class or type specifier

/tmp/luarocks_oxnn-scm-1-943/oxnn/src/LSTM12Part2.cu(103): error: expected a ";"

/tmp/luarocks_oxnn-scm-1-943/oxnn/src/LSTM12Part2.cu(115): warning: parsing restarts here after previous syntax error
```

After the 102-th line in LSTM12Part2.cu, which is

```
 __thrust_hd_warning_disable__
```

,is commented out,  the compiling becomes successful.

Do we need to omit the line?

**Comment by paidi** [comment]
As far as I can see,  `__thrust_hd_warning_disable__` has been removed from thrust in CUDA 7.5. Maybe it is no longer necessary?
